[package]
name = "localdesk-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
localdesk-domain.workspace = true
localdesk-telemetry-helper-protocol.workspace = true
libc.workspace = true
nix.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
